DROP DATABASE BANQUETERA;
CREATE DATABASE BANQUETERA;
USE BANQUETERA;
 
CREATE TABLE ROL (
    ID          BIGINT       NOT NULL AUTO_INCREMENT,
    NOMBRE      VARCHAR(50)  NOT NULL,
    DESCRIPCION VARCHAR(100),
    ACCIONES    TEXT         NOT NULL,
    VALOR_HORA  INT          NOT NULL,
    PRIMARY KEY (ID)
);
 
-- ─── CUENTA ───────────────────────────────────────────────────────────────────
 
CREATE TABLE CUENTA (
    ID             BIGINT       NOT NULL AUTO_INCREMENT,
    EMAIL          VARCHAR(150) NOT NULL,
    CONTRASENIA    VARCHAR(200) NOT NULL,
    ESTADO         CHAR(1),
    FECHA_CREACION TIMESTAMP    NOT NULL,
    ROL_ID         BIGINT       NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_CUENTA_ROL FOREIGN KEY (ROL_ID) REFERENCES ROL(ID),
    CONSTRAINT UK_EMAIL UNIQUE KEY(CONTRASENIA)
);
 
-- ─── TAREA ────────────────────────────────────────────────────────────────────
 
CREATE TABLE TAREA (
    ID          BIGINT       NOT NULL AUTO_INCREMENT,
    ID_CUENTA   BIGINT       NOT NULL,
    NOMBRE      VARCHAR(50)  NOT NULL,
    DESCRIPCION VARCHAR(100),
    FECHA       DATE         NOT NULL,
    ESTADO      CHAR(1)      NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_tarea_trab FOREIGN KEY (ID_CUENTA) REFERENCES CUENTA(ID)
);
 
-- ─── DATOS_USUARIO ────────────────────────────────────────────────────────────
 
CREATE TABLE DATOS_USUARIO (
    CUENTA_ID        BIGINT       NOT NULL,
    NOMBRE           VARCHAR(50)  NOT NULL,
    APELLIDO         VARCHAR(50)  NOT NULL,
    TELEFONO         VARCHAR(8)   NOT NULL,
    DIRECCION        VARCHAR(100) NOT NULL,
    FECHA_NACIMIENTO DATE         NOT NULL,
    PRIMARY KEY (CUENTA_ID),
    CONSTRAINT FK_DATOS_USUARIO_CUENTA FOREIGN KEY (CUENTA_ID) REFERENCES CUENTA(ID)
);
 

 
-- ─── DIETAS_ALERGIAS ──────────────────────────────────────────────────────────
 
CREATE TABLE DIETAS_ALERGIAS (
    ID     BIGINT      NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    TIPO   VARCHAR(2)  NOT NULL,
    PRIMARY KEY (ID)
);
 
-- ─── ACTA ─────────────────────────────────────────────────────────────────────
 
CREATE TABLE ACTA (
    ID               BIGINT  NOT NULL AUTO_INCREMENT,
    BARRA_ALIMENTOS  CHAR(1) NOT NULL,
    BARRA_ALCOHOL    CHAR(1) NOT NULL,
    FORMATO_ALIMENTO CHAR(1) NOT NULL,
    OBSERVACIONES    VARCHAR(200),
    PRIMARY KEY (ID)
);
 
-- ─── EVENTO ───────────────────────────────────────────────────────────────────
 
CREATE TABLE EVENTO (
    ID                 BIGINT      NOT NULL AUTO_INCREMENT,
    TIPO_EVENTO        VARCHAR(50) NOT NULL,
    FECHA_EVENTO       DATE        NOT NULL,
    TERMINO_EVENTO     DATE        NOT NULL,
    TIPO_ESPACIO       CHAR(1),
    CANTIDAD_INVITADOS BIGINT      NOT NULL,
    FECHA_COTIZACION   TIMESTAMP   NOT NULL,
    ESTADO             CHAR(1)     NOT NULL,
    ACTA_ID            BIGINT      NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UK_EVENTO_ACTA UNIQUE KEY (ACTA_ID),
    CONSTRAINT FK_EVENTO_ACTA FOREIGN KEY (ACTA_ID) REFERENCES ACTA(ID)
);
 
-- ─── CALCULOS ─────────────────────────────────────────────────────────────────
 
CREATE TABLE CALCULOS (
    ID               BIGINT,
    CANT_CHEFS       INT,
    LIQUIDO_MIN      INT,
    PORCION          INT,
    COSTE_ALIMENTO   INT,
    COSTE_PERSONAL   INT,
    COSTE_TRANSPORTE INT,
    COSTE_TOTAL      INT,
    CONSTRAINT FK_CALCULOS_EVENTO FOREIGN KEY(ID) REFERENCES EVENTO(ID),
    CONSTRAINT Uk_key UNIQUE Key(id)
);
 
-- ─── ACTA_BEBESTIBLES (tabla intermedia) ──────────────────────────────────────
-- BEBESTIBLES_ID referencia al microservicio de ingredientes (solo se guarda el ID)
 
CREATE TABLE ACTA_BEBESTIBLES (
    ACTA_ID        BIGINT NOT NULL,
    BEBESTIBLES_ID BIGINT NOT NULL,
    PRIMARY KEY (ACTA_ID, BEBESTIBLES_ID),
    CONSTRAINT FK_AB_ACTA FOREIGN KEY (ACTA_ID) REFERENCES ACTA(ID)
);
 
-- ─── ACTA_DIETA_ALERGIA (tabla intermedia) ────────────────────────────────────
 
CREATE TABLE ACTA_DIETA_ALERGIA (
    ACTA_ID            BIGINT NOT NULL,
    DIETAS_ALERGIAS_ID BIGINT NOT NULL,
    PRIMARY KEY (ACTA_ID, DIETAS_ALERGIAS_ID),
    CONSTRAINT FK_ADA_ACTA  FOREIGN KEY (ACTA_ID)            REFERENCES ACTA(ID),
    CONSTRAINT FK_ADA_DIETA FOREIGN KEY (DIETAS_ALERGIAS_ID) REFERENCES DIETAS_ALERGIAS(ID)
);
 
-- ─── ACTA_PLATILLOS (tabla intermedia) ────────────────────────────────────────
-- PLATILLOS_ID referencia al microservicio de ingredientes (solo se guarda el ID)
 
CREATE TABLE ACTA_PLATILLOS (
    ACTA_ID      BIGINT NOT NULL,
    PLATILLOS_ID BIGINT NOT NULL,
    PRIMARY KEY (ACTA_ID, PLATILLOS_ID),
    CONSTRAINT FK_AP_ACTA FOREIGN KEY (ACTA_ID) REFERENCES ACTA(ID)
);
 
-- ─── CUENTA_EVENTO (tabla intermedia) ─────────────────────────────────────────
-- CUENTA_ID referencia al microservicio de cuentainfo (solo se guarda el ID)
 
CREATE TABLE CUENTA_EVENTO (
    EVENTO_ID BIGINT NOT NULL,
    CUENTA_ID BIGINT NOT NULL,
    PRIMARY KEY (EVENTO_ID, CUENTA_ID),
    CONSTRAINT FK_CE_EVENTO FOREIGN KEY (EVENTO_ID) REFERENCES EVENTO(ID)
);
 

 
-- ─── INGREDIENTE ──────────────────────────────────────────────────────────────
 
CREATE TABLE INGREDIENTE (
    ID      BIGINT      NOT NULL AUTO_INCREMENT,
    NOMBRE  VARCHAR(50) NOT NULL,
    ALERGIA VARCHAR(2)  NOT NULL,
    VALOR_K INT         NOT NULL,
    PRIMARY KEY (ID)
);
 
-- ─── BEBESTIBLE ───────────────────────────────────────────────────────────────
 
CREATE TABLE BEBESTIBLE (
    ID          BIGINT      NOT NULL AUTO_INCREMENT,
    NOMBRE      VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(100),
    ALCOHOLICA  CHAR(1)     NOT NULL,
    PRIMARY KEY (ID)
);
 
-- ─── PLATILLO ─────────────────────────────────────────────────────────────────
 
CREATE TABLE PLATILLO (
    ID          BIGINT      NOT NULL AUTO_INCREMENT,
    NOMBRE      VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(100),
    DIETA       VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);
 
-- ─── PASTEL ───────────────────────────────────────────────────────────────────
-- NOTA: referencia ACTA(ID), que vive en banqueteria_evento (otra base de datos)
 
CREATE TABLE PASTEL (
    ID          BIGINT      NOT NULL AUTO_INCREMENT,
    NOMBRE      VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(200),
    ID_ACTA     BIGINT,
    PRIMARY KEY (ID),
    CONSTRAINT FK_ACTA_PASTEL FOREIGN KEY (ID_ACTA) REFERENCES banqueteria_evento.ACTA(ID)
);
 
-- ─── PASTEL_INGR (tabla intermedia) ──────────────────────────────────────────
 
CREATE TABLE PASTEL_INGR (
    PASTEL_ID      BIGINT NOT NULL,
    INGREDIENTE_ID BIGINT NOT NULL,
    PRIMARY KEY (PASTEL_ID, INGREDIENTE_ID),
    CONSTRAINT FK_PI_PASTEL FOREIGN KEY (PASTEL_ID)      REFERENCES PASTEL(ID),
    CONSTRAINT FK_PI_ING    FOREIGN KEY (INGREDIENTE_ID) REFERENCES INGREDIENTE(ID)
);
 
-- ─── PLATILLO_INGREDIENTE (tabla intermedia) ──────────────────────────────────
 
CREATE TABLE PLATILLO_INGREDIENTE (
    PLATILLO_ID    BIGINT NOT NULL,
    INGREDIENTE_ID BIGINT NOT NULL,
    PRIMARY KEY (PLATILLO_ID, INGREDIENTE_ID),
    CONSTRAINT FK_PLAT_ING_PLAT FOREIGN KEY (PLATILLO_ID)    REFERENCES PLATILLO(ID),
    CONSTRAINT FK_PLAT_ING_ING  FOREIGN KEY (INGREDIENTE_ID) REFERENCES INGREDIENTE(ID)
);